# Generated by Django 3.2.14 on 2022-08-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Имя тэга')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Слаг тэга')),
                ('color', models.CharField(max_length=256, unique=True, verbose_name='Цвет тэга')),
            ],
        ),
    ]
