# Generated by Django 3.2.14 on 2022-08-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220802_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='api/images/recipes/', verbose_name='Картинка'),
        ),
    ]
