# Generated by Django 3.2.14 on 2022-08-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient_to_recipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='ingredient_to_recipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ings_ref', to='api.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ing_recipe', through='api.Ingredient_to_Recipe', to='api.Ingredient'),
        ),
        migrations.CreateModel(
            name='Tag_to_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_ref', to='api.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tag_recipe', through='api.Tag_to_Recipe', to='api.Tag'),
        ),
    ]
